services:
  webapp:
    container_name: shop
    hostname: shop
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/public
    depends_on:
      - shop_db
  shop_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: shopdb
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - "./sql/shopdb.sql:/docker-entrypoint-initdb.d/1.sql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: shop_db
    depends_on:
      - shop_db
